#!/usr/bin/env python3
"""
Inferemote: a Remote Inference Toolkit for Ascend 310

Copyright (c) 2021 Jiasheng Hao <haojiash@qq.com>
(University of Electronic Science and Technology of China, UESTC)

Permission  is  hereby  granted,  free  of  charge,  to  any  person
obtaining a copy of this software and associated documentation files
(the  "Software"),  to deal  in  the  Software without  restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software,
and to  permit persons to whom  the Software is furnished  to do so,
subject to the following conditions:

The  above copyright  notice  and this  permission  notice shall  be
included in all copies or substantial portions of the Software.

THE  SOFTWARE IS  PROVIDED "AS  IS", WITHOUT  WARRANTY OF  ANY KIND,
EXPRESS OR IMPLIED,  INCLUDING BUT NOT LIMITED TO  THE WARRANTIES OF
MERCHANTABILITY,    FITNESS   FOR    A   PARTICULAR    PURPOSE   AND
NONINFRINGEMENT. IN NO EVENT SHALL  THE AUTHORS OR COPYRIGHT HOLDERS
BE LIABLE FOR  ANY CLAIM, DAMAGES OR OTHER LIABILITY,  WHETHER IN AN
ACTION OF  CONTRACT, TORT OR OTHERWISE,  ARISING FROM, OUT OF  OR IN
CONNECTION WITH  THE SOFTWARE OR  THE USE  OR OTHER DEALINGS  IN THE
SOFTWARE.

"""
import os, sys
import numpy as np
from inferemote.model_service import ModelService
service, args = ModelService.Create(__name__)

from inferemote.atlas_model import AtlasModel
from inferemote.ccbuf2numpy import Numpy2Ccbuf

class AclliteModel(AtlasModel):
   ''' Based on AclLite '''

   def inference(self, blob):

       if len(blob) == 1: #get_info()
           output = [b"AtalsModel"]

       else:
           blob = np.frombuffer(blob)
           output = self.model.execute([blob])

       output = Numpy2Ccbuf(output)

       return output

if __name__ == '__main__':
    model_file = args['model_file']
    if not os.path.exists(model_file):
       print("Error: `model_file ({})' is None or not found on this earth!".format(model_file))
       sys.exit()

    model = AclliteModel(model_file)
    service.Run(model)

# Ends.
