#!/usr/bin/env python3
import argparse
from inferemote.remote_factory import RemoteFactory

def _parse_args():
        ap = argparse.ArgumentParser()
        ap.add_argument("-r", "--remote", #required=True,
            help="the remote model location, such as 'picasso@113.54.160.253', '5551@localhost', 'http://localhost:8000', or '@localhost:tcp:5551'")
        args = vars(ap.parse_args())
        return args['remote']

if __name__ == '__main__':

    rmt = _parse_args()
    remote = RemoteFactory.create(rmt)
    print("REMOTE ({}):\n{}".format(rmt, remote.get_info()))
